package devsync

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"filippo.io/age"
	"filippo.io/age/agessh"
	"github.com/zalando/go-keyring"
	"golang.org/x/crypto/ssh"
)

// Every sync file is encrypted to one data key: an age identity generated by
// `holocron sync init`. The data key is stored in the sync folder only in
// wrapped form, once for each unlock method chosen (a passphrase, SSH keys).
// A computer unlocks it once and keeps it in the OS keychain.
// See docs/adr/0007-multi-device-sync.md.

// ErrLocked means the data key is not available on this computer.
var ErrLocked = errors.New("sync is locked on this computer")

// keyID is a short, non-secret fingerprint of a data key.
func keyID(id *age.HybridIdentity) string {
	sum := sha256.Sum256([]byte(id.Recipient().String()))
	return hex.EncodeToString(sum[:6])
}

func newDataKey() (*age.HybridIdentity, error) { return age.GenerateHybridIdentity() }

func parseDataKey(s string) (*age.HybridIdentity, error) {
	id, err := age.ParseHybridIdentity(strings.TrimSpace(s))
	if err != nil {
		return nil, fmt.Errorf("that is not a Holocron sync key (it starts with AGE-SECRET-KEY-PQ-1): %w", err)
	}
	return id, nil
}

// Keychain caches data keys per sync set. Several keys may be kept (newest
// first) while files encrypted with a rotated key are still around.
type Keychain interface {
	Get(set string) ([]string, error)
	Set(set string, keys []string) error
	Delete(set string) error
}

// SystemKeychain uses the OS keychain: Windows Credential Manager, the macOS
// Keychain or the Secret Service on Linux.
type SystemKeychain struct{}

const keychainService = "holocron-sync"

func (SystemKeychain) Get(set string) ([]string, error) {
	v, err := keyring.Get(keychainService, set)
	if errors.Is(err, keyring.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return strings.Fields(v), nil
}

func (SystemKeychain) Set(set string, keys []string) error {
	return keyring.Set(keychainService, set, strings.Join(keys, "\n"))
}

func (SystemKeychain) Delete(set string) error {
	err := keyring.Delete(keychainService, set)
	if errors.Is(err, keyring.ErrNotFound) {
		return nil
	}
	return err
}

// MemoryKeychain keeps keys for the life of the process; used where no OS
// keychain is available, and in tests.
type MemoryKeychain map[string][]string

func (m MemoryKeychain) Get(set string) ([]string, error) { return m[set], nil }
func (m MemoryKeychain) Set(set string, keys []string) error {
	m[set] = keys
	return nil
}
func (m MemoryKeychain) Delete(set string) error { delete(m, set); return nil }

// ScryptWorkFactor is age's passphrase cost (2^n). Tests lower it.
var ScryptWorkFactor = 18

// wrapWithPassphrase encrypts the data key with a passphrase.
func wrapWithPassphrase(key *age.HybridIdentity, passphrase string) ([]byte, error) {
	if len(passphrase) < 8 {
		return nil, errors.New("use a passphrase of at least 8 characters")
	}
	r, err := age.NewScryptRecipient(passphrase)
	if err != nil {
		return nil, err
	}
	r.SetWorkFactor(ScryptWorkFactor)
	return encryptBytes([]byte(key.String()), r)
}

// wrapWithSSH encrypts the data key to an SSH public key (an authorized_keys
// line, as in id_ed25519.pub).
func wrapWithSSH(key *age.HybridIdentity, publicKey string) (name string, data []byte, err error) {
	r, err := agessh.ParseRecipient(strings.TrimSpace(publicKey))
	if err != nil {
		return "", nil, fmt.Errorf("not a usable SSH public key (ssh-ed25519 or ssh-rsa): %w", err)
	}
	pk, _, _, _, err := ssh.ParseAuthorizedKey([]byte(publicKey))
	if err != nil {
		return "", nil, err
	}
	sum := sha256.Sum256(pk.Marshal())
	data, err = encryptBytes([]byte(key.String()), r)
	return "ssh-" + hex.EncodeToString(sum[:6]) + ".age", data, err
}

// sshIdentity loads an SSH private key for unwrapping. passphrase is asked
// for only if the key is encrypted.
func sshIdentity(path string, passphrase func() ([]byte, error)) (age.Identity, error) {
	pemBytes, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	id, err := agessh.ParseIdentity(pemBytes)
	var missing *ssh.PassphraseMissingError
	if errors.As(err, &missing) {
		pub := missing.PublicKey
		if pub == nil {
			pubBytes, perr := os.ReadFile(path + ".pub")
			if perr != nil {
				return nil, fmt.Errorf("%s is encrypted and its public key (%s.pub) could not be read: %w", path, path, perr)
			}
			if pub, _, _, _, perr = ssh.ParseAuthorizedKey(pubBytes); perr != nil {
				return nil, perr
			}
		}
		if passphrase == nil {
			return nil, fmt.Errorf("%s is protected by a passphrase", path)
		}
		return agessh.NewEncryptedSSHIdentity(pub, pemBytes, passphrase)
	}
	if err != nil {
		return nil, fmt.Errorf("reading SSH key %s: %w", path, err)
	}
	return id, nil
}

// unwrap tries an identity against every wrapped copy of the data key.
func unwrap(keysDir string, prefix string, id age.Identity) (*age.HybridIdentity, error) {
	files, _ := filepath.Glob(filepath.Join(keysDir, prefix+"*.age"))
	if len(files) == 0 {
		return nil, fmt.Errorf("the sync folder has no %s unlock set up", strings.TrimSuffix(prefix, "-"))
	}
	var lastErr error
	for _, f := range files {
		data, err := os.ReadFile(f)
		if err != nil {
			lastErr = err
			continue
		}
		plain, err := decryptBytes(data, id)
		if err != nil {
			lastErr = err
			continue
		}
		return parseDataKey(string(plain))
	}
	var noMatch *age.NoIdentityMatchError
	if errors.As(lastErr, &noMatch) {
		return nil, errors.New("that does not unlock this sync folder")
	}
	return nil, fmt.Errorf("unlocking: %w", lastErr)
}

// runKeyCommand runs a configured key_command and returns its output.
func runKeyCommand(argv []string) (string, error) {
	if len(argv) == 0 {
		return "", errors.New("no key_command configured")
	}
	cmd := exec.Command(argv[0], argv[1:]...)
	var out, errOut bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &errOut
	if err := cmd.Run(); err != nil {
		msg := strings.TrimSpace(errOut.String())
		if msg != "" {
			return "", fmt.Errorf("sync.key_command failed: %w: %s", err, msg)
		}
		return "", fmt.Errorf("sync.key_command failed: %w", err)
	}
	return strings.TrimSpace(out.String()), nil
}

func encryptBytes(plain []byte, recipients ...age.Recipient) ([]byte, error) {
	var buf bytes.Buffer
	w, err := age.Encrypt(&buf, recipients...)
	if err != nil {
		return nil, err
	}
	if _, err := w.Write(plain); err != nil {
		return nil, err
	}
	if err := w.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func decryptBytes(data []byte, ids ...age.Identity) ([]byte, error) {
	r, err := age.Decrypt(bytes.NewReader(data), ids...)
	if err != nil {
		return nil, err
	}
	return io.ReadAll(r)
}
